import {
    AccountAttribute,
    DEFAULT_ACCOUNT_ATTRIBUTES,
    WizardState,
} from '../../saas-connectivity-creator/saas-connectivity-creator.models';
import { CanvasSnapshot } from '../models/canvas-state';
import {
    ApiRequestNodeData,
    ConnectorNodeData,
    DataTransformNodeData,
    PaginationNodeData,
} from '../models/node-types';

const CONNECTOR_NAME = 'custom-sailpoint-connector';
const DEFAULT_API_PATH = '/users';
const DEFAULT_BASE_URL = 'https://api.example.com';

export interface CanvasMappingResult {
    state: WizardState;
    pipelineOrder: string[];
    apiEndpoint: string;
    apiPath: string;
    httpMethod: string;
    apiHeaders: { key: string; value: string }[];
    pagination?: PaginationNodeData['config'];
    mappings: { source: string; target: string }[];
}

function resolveEndpoint(endpoint: string): { baseUrl: string; apiPath: string } {
    const trimmed = endpoint.trim();
    if (!trimmed) {
        return { baseUrl: DEFAULT_BASE_URL, apiPath: DEFAULT_API_PATH };
    }

    try {
        const url = new URL(trimmed);
        const path = `${url.pathname}${url.search}`;
        return {
            baseUrl: `${url.protocol}//${url.host}`,
            apiPath: path.length > 1 ? path : DEFAULT_API_PATH,
        };
    } catch {
        const apiPath = trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
        return { baseUrl: DEFAULT_BASE_URL, apiPath };
    }
}

function buildAccountAttributes(mappings: { source: string; target: string }[]): AccountAttribute[] {
    if (mappings.length === 0) {
        return DEFAULT_ACCOUNT_ATTRIBUTES.map((attr) => ({ ...attr }));
    }

    return mappings.map((mapping) => ({
        name: mapping.target,
        type: 'string' as const,
        description: `Mapped from source field "${mapping.source}"`,
        multi: false,
        entitlement: false,
        managed: false,
    }));
}

function topologicalOrder(snapshot: CanvasSnapshot): string[] {
    const nodeIds = snapshot.nodes.map((n) => n.id);
    const incoming = new Map<string, number>();
    const adjacency = new Map<string, string[]>();

    for (const id of nodeIds) {
        incoming.set(id, 0);
        adjacency.set(id, []);
    }

    for (const edge of snapshot.edges) {
        if (!incoming.has(edge.target) || !adjacency.has(edge.source)) {
            continue;
        }
        incoming.set(edge.target, (incoming.get(edge.target) ?? 0) + 1);
        adjacency.get(edge.source)!.push(edge.target);
    }

    const queue = nodeIds.filter((id) => (incoming.get(id) ?? 0) === 0);
    const order: string[] = [];

    while (queue.length > 0) {
        const current = queue.shift()!;
        order.push(current);
        for (const next of adjacency.get(current) ?? []) {
            const count = (incoming.get(next) ?? 1) - 1;
            incoming.set(next, count);
            if (count === 0) {
                queue.push(next);
            }
        }
    }

    const remaining = nodeIds.filter((id) => !order.includes(id));
    return [...order, ...remaining];
}

function findNodeData<T extends ConnectorNodeData['nodeType']>(
    snapshot: CanvasSnapshot,
    nodeType: T,
): Extract<ConnectorNodeData, { nodeType: T }> | null {
    const node = snapshot.nodes.find((n) => n.data.nodeType === nodeType);
    return (node?.data as Extract<ConnectorNodeData, { nodeType: T }>) ?? null;
}

export function mapCanvasToWizardState(snapshot: CanvasSnapshot): CanvasMappingResult {
    const apiData = findNodeData(snapshot, 'api-request');
    const transformData = findNodeData(snapshot, 'data-transform');
    const paginationData = findNodeData(snapshot, 'pagination');

    const endpoint = apiData?.config.endpoint?.trim() ?? '';
    const { baseUrl, apiPath } = resolveEndpoint(endpoint);
    const method = apiData?.config.method ?? 'GET';
    const apiHeaders = (apiData?.config.headers ?? []).filter((h) => h.key || h.value);
    const mappings = transformData?.config.mappings ?? [{ source: 'id', target: 'identity' }];
    const accountAttributes = buildAccountAttributes(mappings);
    const identityAttribute = mappings[0]?.target ?? 'identity';
    const pipelineOrder = topologicalOrder(snapshot);

    const state: WizardState = {
        connectorName: CONNECTOR_NAME,
        displayName: 'Custom SailPoint Connector',
        description: 'Generated by the SailPoint Visual Connector Builder prototype',
        keyType: 'simple',
        supportsStatefulCommands: false,
        authType: 'apiKey',
        authConfig: {
            apiUrl: baseUrl,
            keyLabel: 'API Key',
        },
        commands: {
            testConnection: true,
            accountList: true,
            accountRead: true,
            accountCreate: false,
            accountUpdate: false,
            accountDelete: false,
            accountEnable: false,
            accountDisable: false,
            accountUnlock: false,
            changePassword: false,
            entitlementList: false,
            entitlementRead: false,
            sourceDataDiscover: false,
            sourceDataRead: false,
        },
        accountAttributes,
        displayAttribute: identityAttribute,
        identityAttribute,
        groupAttribute: '',
        entitlementAttributes: [],
        entitlementDisplayAttribute: 'name',
        entitlementIdentityAttribute: 'id',
        accountCreateFields: [],
        additionalConfig: [
            {
                sectionTitle: 'API Configuration',
                sectionHelpMessage: 'Endpoint and HTTP settings generated from the visual builder canvas',
                items: [
                    {
                        key: 'apiEndpoint',
                        label: 'API Endpoint Path',
                        type: 'text',
                        required: true,
                    },
                    {
                        key: 'httpMethod',
                        label: 'HTTP Method',
                        type: 'text',
                        required: true,
                    },
                ],
            },
        ],
    };

    return {
        state,
        pipelineOrder,
        apiEndpoint: endpoint.startsWith('http') ? endpoint : `${baseUrl}${apiPath}`,
        apiPath,
        httpMethod: method,
        apiHeaders,
        pagination: paginationData?.config,
        mappings,
    };
}

export function injectVisualBuilderMetadata(
    indexTs: string,
    mapping: CanvasMappingResult,
): string {
    const header = `// Generated by SailPoint Visual Connector Builder [PROTOTYPE]
// Pipeline order: ${mapping.pipelineOrder.join(' -> ') || 'none'}
// API: ${mapping.httpMethod} ${mapping.apiEndpoint}
// API path: ${mapping.apiPath}
${mapping.pagination ? `// Pagination: ${mapping.pagination.strategy}, pageSize=${mapping.pagination.pageSize}` : ''}
// Attribute mappings: ${mapping.mappings.map((m) => `${m.source} -> ${m.target}`).join(', ')}

`;

    return header + indexTs;
}
