import {
    AccountAttribute,
    DEFAULT_ACCOUNT_ATTRIBUTES,
    WizardState,
} from '../../saas-connectivity-creator/saas-connectivity-creator.models';
import { CanvasSnapshot } from '../models/canvas-state';
import {
    ApiRequestNodeData,
    ConnectorNodeData,
    DataTransformNodeData,
    PaginationNodeData,
} from '../models/node-types';

const CONNECTOR_NAME = 'custom-sailpoint-connector';

export interface CanvasMappingResult {
    state: WizardState;
    pipelineOrder: string[];
    apiEndpoint: string;
    httpMethod: string;
    pagination?: PaginationNodeData['config'];
    mappings: { source: string; target: string }[];
}

function getBaseUrl(endpoint: string): string {
    try {
        const url = new URL(endpoint);
        return `${url.protocol}//${url.host}`;
    } catch {
        const slashIndex = endpoint.indexOf('/', 8);
        return slashIndex > 0 ? endpoint.slice(0, slashIndex) : endpoint;
    }
}

function buildAccountAttributes(mappings: { source: string; target: string }[]): AccountAttribute[] {
    if (mappings.length === 0) {
        return DEFAULT_ACCOUNT_ATTRIBUTES.map((attr) => ({ ...attr }));
    }

    return mappings.map((mapping) => ({
        name: mapping.target,
        type: 'string' as const,
        description: `Mapped from source field "${mapping.source}"`,
        multi: false,
        entitlement: false,
        managed: false,
    }));
}

function topologicalOrder(snapshot: CanvasSnapshot): string[] {
    const nodeIds = snapshot.nodes.map((n) => n.id);
    const incoming = new Map<string, number>();
    const adjacency = new Map<string, string[]>();

    for (const id of nodeIds) {
        incoming.set(id, 0);
        adjacency.set(id, []);
    }

    for (const edge of snapshot.edges) {
        if (!incoming.has(edge.target) || !adjacency.has(edge.source)) {
            continue;
        }
        incoming.set(edge.target, (incoming.get(edge.target) ?? 0) + 1);
        adjacency.get(edge.source)!.push(edge.target);
    }

    const queue = nodeIds.filter((id) => (incoming.get(id) ?? 0) === 0);
    const order: string[] = [];

    while (queue.length > 0) {
        const current = queue.shift()!;
        order.push(current);
        for (const next of adjacency.get(current) ?? []) {
            const count = (incoming.get(next) ?? 1) - 1;
            incoming.set(next, count);
            if (count === 0) {
                queue.push(next);
            }
        }
    }

    const remaining = nodeIds.filter((id) => !order.includes(id));
    return [...order, ...remaining];
}

function findNodeData<T extends ConnectorNodeData['nodeType']>(
    snapshot: CanvasSnapshot,
    nodeType: T,
): Extract<ConnectorNodeData, { nodeType: T }> | null {
    const node = snapshot.nodes.find((n) => n.data.nodeType === nodeType);
    return (node?.data as Extract<ConnectorNodeData, { nodeType: T }>) ?? null;
}

export function mapCanvasToWizardState(snapshot: CanvasSnapshot): CanvasMappingResult {
    const apiData = findNodeData(snapshot, 'api-request');
    const transformData = findNodeData(snapshot, 'data-transform');
    const paginationData = findNodeData(snapshot, 'pagination');

    const endpoint = apiData?.config.endpoint?.trim() ?? '';
    const method = apiData?.config.method ?? 'GET';
    const mappings = transformData?.config.mappings ?? [{ source: 'id', target: 'identity' }];
    const accountAttributes = buildAccountAttributes(mappings);
    const identityAttribute = mappings[0]?.target ?? 'identity';
    const pipelineOrder = topologicalOrder(snapshot);

    const state: WizardState = {
        connectorName: CONNECTOR_NAME,
        displayName: 'Custom SailPoint Connector',
        description: 'Generated by the SailPoint Visual Connector Builder prototype',
        keyType: 'simple',
        supportsStatefulCommands: false,
        authType: 'apiKey',
        authConfig: {
            apiUrl: endpoint ? getBaseUrl(endpoint) : 'https://api.example.com',
            keyLabel: 'API Key',
        },
        commands: {
            testConnection: true,
            accountList: true,
            accountRead: true,
            accountCreate: false,
            accountUpdate: false,
            accountDelete: false,
            accountEnable: false,
            accountDisable: false,
            accountUnlock: false,
            changePassword: false,
            entitlementList: false,
            entitlementRead: false,
            sourceDataDiscover: false,
            sourceDataRead: false,
        },
        accountAttributes,
        displayAttribute: identityAttribute,
        identityAttribute,
        groupAttribute: '',
        entitlementAttributes: [],
        entitlementDisplayAttribute: 'name',
        entitlementIdentityAttribute: 'id',
        accountCreateFields: [],
        additionalConfig: endpoint
            ? [
                  {
                      sectionTitle: 'API Configuration',
                      sectionHelpMessage: 'Visual builder generated API settings',
                      items: [
                          {
                              key: 'apiEndpoint',
                              label: 'API Endpoint',
                              type: 'url',
                              required: true,
                          },
                          {
                              key: 'httpMethod',
                              label: 'HTTP Method',
                              type: 'text',
                              required: true,
                          },
                      ],
                  },
              ]
            : [],
    };

    return {
        state,
        pipelineOrder,
        apiEndpoint: endpoint,
        httpMethod: method,
        pagination: paginationData?.config,
        mappings,
    };
}

export function injectVisualBuilderMetadata(
    indexTs: string,
    mapping: CanvasMappingResult,
): string {
    const header = `// Generated by SailPoint Visual Connector Builder [PROTOTYPE]
// Pipeline order: ${mapping.pipelineOrder.join(' -> ') || 'none'}
// API: ${mapping.httpMethod} ${mapping.apiEndpoint || '(not configured)'}
${mapping.pagination ? `// Pagination: ${mapping.pagination.strategy}, pageSize=${mapping.pagination.pageSize}` : ''}
// Attribute mappings: ${mapping.mappings.map((m) => `${m.source} -> ${m.target}`).join(', ')}

`;

    const mappingBlock = mapping.mappings
        .map((m) => `    // ${m.source} -> ${m.target}`)
        .join('\n');

    const withMappings = indexTs.replace(
        'const myClient = new',
        `${mappingBlock ? `${mappingBlock}\n\n    const myClient = new` : 'const myClient = new'}`,
    );

    return header + withMappings;
}
